### ISSUE TITLE
Не работает хук cssToPage.php

### ISSUE THREAD

**Issue by ulin-evgeny** [sergant210/MinifyX#6]
Скачал плагин с репозитория, установил. Написал такой код:
```
[[!MinifyX? 
    &minifyCss=`1`
    &hook=`cssToPage.php`
    &cssSources=`
        assets/template/css/all.css,
    `
]]
[[+MinifyX.css]]
```
За счет хука cssToPage.php стили должны быть в шапке - внутри тега <style>. Но этого не произошло. Стили подключаются также, как если бы я не указывал этот хук (через файл). Я пробовал убирать плейсхолдер [[+MinifyX.css]] - ничего не изменилось.

Плагин скачал именно с modstore.pro (Если скачивать с modx.com, то папки hooks вообще нет. У меня же она есть).

Что я сделал не так?

**Comment by sergant210** [comment]
> Что я сделал не так?

Любой вариант на выбор - 
- Не прочитал [документацию](https://docs.modx.pro/komponentyi/minifyx/snippet#%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B) про параметры. 
- Не подсмотрел в параметрах сниппета как правильно называется параметр для хуков.

**Comment by ulin-evgeny** [comment]
Вместо hook написал hooks, и все заработало. Спасибо :-) .
Я просто на этой странице: https://modstore.pro/packages/utilities/minifyx#tab/changelog, в истории изменений увидел такую строку:

> Added file hook "cssToPage" (&hook=`cssToPage.php`).

Я ее и скопировал. Но, видимо, в ней опечатка опечатка.
